### ISSUE TITLE
Strange behavior of the pyspssio package with pipx

### ISSUE THREAD

**Issue by ap-Codkelden** [stspec/pyspssio#7]
I tried to install `pyspssio` with pipx **into existing** venv:

    pipx inject <venv> pyspssio

No error messages were received, but I was unable to import `pyspssio`, and package wasn't present in the `pip freeze` output. This was strange, and I decided to explore more by entering into the venv.

I invoked that:

    pipx install git+https://github.com/stspec/pyspssio.git

and got a message:

```
Note: Dependent package 'numpy' contains 1 apps
  - f2py

No apps associated with package pyspssio. Try again with '--include-deps' to
include apps of dependent packages, which are listed above. If you are
attempting to install a library, pipx should not be used. Consider using pip
or a similar tool instead.
```
After that, I used  `--include-deps` as recommended, and the package was installed by pipx **as a new venv**: 

```
package pyspssio 0.4.3+1.ga4cedda, installed using Python 3.11.8
    - f2py
```
Now I can import it and read `*.sav` file), but the package is still absent in both `pip freeze ` and in `pipx list` output.

* Python: 3.11.8
* OS: GNU/Linux x86_64

**Comment by stspec** [comment]
I'm not that familiar with pipx, but it seems this package isn't compatible due to not having a console_scripts entry point. 

I've created a separate branch for now with cli support here: https://github.com/stspec/pyspssio/tree/cli-support. Are you able to test installing from that branch?

**Comment by ap-Codkelden** [comment]
Hi, Steven!

Thank you for your corrections. 
I try to install `pyspssio` from the Git branch provided with the given command:

    pipx inject <venv> git+https://github.com/stspec/pyspssio.git@cli-support

Eventually, the `pyspssio` package was installed into the venv (so I could `import pyspssio` it and read a SAV file), but it is still absent from the list of packages returned by the `pipx list` command.

Along with it `pyspssio` is present under `~/.local/pipx/venvs/<venv>/bin `. When I try to execute it, I got an error:

```
./pyspssio                                                                                    
Traceback (most recent call last):
  File "/home/<user>/.local/pipx/venvs/<venv>/bin/./pyspssio", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/<user>/.local/pipx/venvs/<venv>/lib/python3.12/site-packages/pyspssio/command_line.py", line 45, in main
    func = getattr(user_functions, sys.argv[1])
                                   ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by stspec** [comment]
@ap-Codkelden I updated that branch with better exception handling.

The command line usage should be something like `pyspssio read_sav --spss_file "data.sav"`.

Does pipx not list the package only when using `pipx inject`? What if you use `pipx install` or start from a fresh venv?

**Comment by stspec** [comment]
It looks like you have to use `pipx list --include-injected` for injected packages to show up.

https://pipx.pypa.io/stable/docs/#pipx-list

**Comment by ap-Codkelden** [comment]
@stspec I apologize I don't know about the ` --include-injected` option.
Now `pyspssio` is listed as an injected package, thank you!

**Comment by stspec** [comment]
No worries. Glad it seems to be working now.

I've made some additional commits to improve CLI support a bit. If your pipx application isn't actually calling pyspssio from the command line, then I don't think it should matter for your use case. I'm expecting to release an alpha or beta next weekend on the main branch with these updates. I'll probably close this issue at that time, but let me know if you run into any other problems.
